### ISSUE TITLE
Ures epg.xml file

### ISSUE THREAD

**Issue by pepev82** [szabbenjamin/ittotttv#10]
"epg.xml ujrairva" uzenet ellenere csak egy ures xml file jon letre. Csak fejlec talalhato benne.

Amugy koszonet a servlet-ert es a raforditott idodert is!

xml-t nem enged, ezert .txt
[epg.txt](https://github.com/szabbenjamin/ittotttv/files/2827039/epg.txt)

**Comment by szabbenjamin** [comment]
Javítva. Kérlek ellenőrizd és jelezz vissza!
https://github.com/szabbenjamin/ittotttv/commit/a932f9414a0e277dba674fb9c42a4c7fef7c7804

**Comment by pepev82** [comment]
Szia!

Nagyon koszonom a hihetetlen gyors reagalast, de sajnos nem indul
egyatalan.
A mellekletben az npm-debug.log.

A log tartalman kivul meg annyit irt szabad forditasban, hogy:
 "Ezt a hibat meg okozhatja a legacy binary "mode" hasznalata.

Majd ezutan arra ker olvasd el a nodjs README.debian fajlt tovabbi
informacioert.


Sajnos En nem vagyok ehhez eleg okos.

Udv:

Peti

Benjamin Szabo <notifications@github.com> ezt írta (időpont: 2019. febr.
5., K, 19:24):

**Comment by szabbenjamin** [comment]
Hali

Nem látom, hogy logot csatoltál volna.

**Comment by pepev82** [comment]
proba...
[npm-debug.log](https://github.com/szabbenjamin/ittotttv/files/2836866/npm-debug.log)

most ?

**Comment by szabbenjamin** [comment]
Próbáld most. 
**engine** mappában **npm start**

**Comment by pepev82** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v8.11.1
4 error Failed to parse json
4 error Unexpected token < in JSON at position 6
5 error File: /home/tv/ittotttv/engine/package.json
6 error Failed to parse package.json data.
6 error package.json must be actual JSON, not just JavaScript.
6 error
6 error This is not a bug in npm.
6 error Tell the package author to fix their package.json file. JSON.parse
7 error System Linux 4.14.79+
8 error command "/usr/bin/node" "/usr/bin/npm" "start"
9 error cwd /home/tv/ittotttv/engine
10 error node -v v8.11.1
11 error npm -v 1.4.21
12 error file /home/tv/ittotttv/engine/package.json
13 error code EJSONPARSE
14 verbose exit [ 1, true ]

**Comment by szabbenjamin** [comment]
Töröld és töltsd le újra és állítsd be a teljes projektet. Korrumpálódott a json fájlod.

**Comment by pepev82** [comment]
Köszönöm, mostmár indul és van epg is.
