### ISSUE TITLE
Új 18.3 Kodi vs ittott servlet

### ISSUE THREAD

**Issue by Sentinel800** [szabbenjamin/ittotttv#11]
Felraktam már a ,,nagy" a digi előd servlet-et, ha már van ingyen teszt az ITTOTT tvre. Az EPG leszedésekor pár csatornánál nem talál EPG-t, de inkább az öregedésével van a fő probléma: 
,,kívülről" MPC\VLC a servletet meg lehet hívni, de az új Kodi nem szereti, hasonló eredményt produkál, mint digi servlet mikor kijött a 18as Kodi, nem tudja megnyitni a streamet.

Az lehet már az ittott tv oldaláról jön, hogy a servlet nem tud csatornalistát és EPG-t generálni működő VPN el, le kellett kapcsolnom.

**Comment by szabbenjamin** [comment]
Nagyjából jövőhéten ilyenkor fogom tudni orvosolni.

**Comment by szab100** [comment]
@Sentinel800 @szabbenjamin En szinten ezekbe a hibakba futottam bele, azt hiszem a legtobb emlitett problemakra megoldast nyujtanak a #12 -ben eszkozolt javitasaim. Aki a PR merge elott kiprobalna, a legegyszerubb az en repomat klonozni: https://github.com/szab100/ittotttv

**Comment by szabbenjamin** [comment]
Elnézést, hogy eddig nem reagáltam, ezen a hétvégén ellenőrzöm és visszajelzek!
