### ISSUE TITLE
Stream URL token + PVR IPTV Simple Client

### ISSUE THREAD

**Issue by tamasdxw** [szabbenjamin/ittotttv#6]
Szia,

az ittott.tv bizonyos streameknel az eddigi io* helyett eco* kezdetu URL-eket ad vissza, egy uj "token" query parameterrel egyutt. Az appod sima 200 OK-t es ures response bodyt ad, mivel az eco* nincs lekezelve a tv_servlet.js-ben. Ezt hozzaadtam, igy mar egy jo 302 redirectet kapok, viszont a PVR IPTV Simple Client amit hasznalok libreelec alatt ugy tunik, a tokent figyelmen kivul hagyja, az eco* stream viszont anelkul nem megy. Tudnal ajanlani egy masik IPTV klienst ami normalisan kezeli a teljes URLt?

Koszi!

**Comment by tamasdxw** [comment]
Update:
mint kiderult, az IPTV Simple Client mukodik, de az ffmpeg SSL hibat dob, updatelnem kell a root CA bundlet. Viszont, a stream mukodik http:// protokollon keresztul is, szoval....lusta leszek :)

**Comment by grape77** [comment]
Szia!

Március óta használom az általad készített ittott tv repót PI3-on OSMC-vel. Kb. egy het azt tapasztalom, hogy egy két adás kivételével nem indulnak el az adások, még a közszolgálatiak sem.  Az ittott tv előfizetésem rendben van, tudok műsort nézni laptopon, vagy telefonon. 

Újrahúztam az OSMC (régebbi és újabb frissétésekkel is) és telepítettem az általad megadottak alapján a connect servletet, de semmi változás. az iptv kliens úgy tűnik rendben van.

Sajnos nem nagyon ismerem a linux világát lelkes amatőrként használom, de ez most kifogott rajtam. Van valami ötleted, hogyan lehetne orvosolni a helyzetet? Köszönöm! Z.

**Comment by szabbenjamin** [comment]
Köszönöm a visszajelzéseket, értem mi a probléma. Mivel jelenleg nincs ittottv előfizetésem így nem tudok gyorsban ránézni.
Ingyenes, 24h időszakot tudok kérni, így lenne egy napom tesztelni és javítania hibákat is. Ehhez viszont találnom kell egy szabad hétvégét, napot - munkával viszont nagyon le vagyok e hetekben terhelve.

Várhatóan 2-3 héten belül jönni fog a javítás részemről (hacsak valaki esetleg be nem előz egy pull request-tel)

**Comment by tamasdxw** [comment]
Kuldtem pull requestet.

**Comment by tamasdxw** [comment]
@grape77 ha nem akarsz varni amig szabbenjamin elfogadja a pull requestet, itt a javitott tv_servlet.js file, amivel ujra mukodnek a streamek:

https://github.com/tamasdxw/ittotttv/blob/master/engine/tv_servlet.js

**Comment by szabbenjamin** [comment]
Köszönöm, elfogadtam!

Ha valakinek van accountja legyen szives visszajelezni, hogy a probléma elhárult-e.

**Comment by grape77** [comment]
Sziasztok!
Köszönöm a segítséget. Accountom van, hamarosan kipróbálom, ha tudom... 
@szabbenjamin: Ez a rész be fog épülni majd a telepítőbe?
(wget https://raw.githubusercontent.com/szabbenjamin/ittotttv/master/osmc_installer.sh && bash osmc_installer.sh)
@tamasdxw: köszi a felajánlást :-) Sajnos nem nagyon értek a linux világához és a programozáshoz. Értelmezhetem úgy, hogy a tv_servlet.js filét valahogy letöltöm és bemásolom az engine mappába, vagy hogyan lehet ezt a scriptet bevarázsolni a rendszer alá? Köszönöm! Z.

**Comment by tamasdxw** [comment]
@grape77 igen, letoltod, bemasolod, majd ujrainditod.
itt a nyers file: https://raw.githubusercontent.com/tamasdxw/ittotttv/master/engine/tv_servlet.js

(becsatoltam ZIP mellekletkent is):
[tv_servlet.js.zip](https://github.com/szabbenjamin/ittotttv/files/2253703/tv_servlet.js.zip)

**Comment by grape77** [comment]
Köszönöm!


________________________________
Feladó: tamasdxw <notifications@github.com>
Elküldve: 2018. augusztus 2., csütörtök 15:37
Címzett: szabbenjamin/ittotttv
Másolatot kap: grape77; Mention
Tárgy: Re: [szabbenjamin/ittotttv] Stream URL token + PVR IPTV Simple Client (#6)


@grape77<https://github.com/grape77> igen, letoltod, bemasolod, majd ujrainditod.
itt a nyers file: https://raw.githubusercontent.com/tamasdxw/ittotttv/master/engine/tv_servlet.js

(becsatoltam ZIP mellekletkent is):
tv_servlet.js.zip<https://github.com/szabbenjamin/ittotttv/files/2253703/tv_servlet.js.zip>

**Comment by szabbenjamin** [comment]
@grape77 
Ha osmc-t használsz:
ssh-n (putty) bejelentkezel
cd /home/osmc/ittotttv
git pull origin master

Ha hibát dob pullozáskor (conflict) akkor a felsorolt fájlokat egyesével törölgesd vagy 
git reset --hard origin/master
és utána csekkold le a config fájlt, indítsd újra a gépet és készen is vagy.

**Comment by grape77** [comment]
Szia

Nekifutottam, feltettem egy új, szűz osmc-t majd ráhúztam az adott forrású ittotttv installt.

A: sajna az iptv configban nem találtam meg az m3u részt, nem tudtam kiválasztani a csatorna listát.

B: kipróbáltam a git pull origin master-t és ezt az üzenetet kaptam: error: cannot open .git/FETCH_HEAD: permission denied (az androidhoz hasonlóan ezt is rootolni kellene...?)

C: próbáltam bemásolni a tv_servlet.js filét az osmc file kezelőjével, de nem engedte, se törölni az eredetit, se felülírni. A másolást usb drivéről akartam végezni igaz .zip alól. A biztonsági mentése a filének az usb penre sikerült.

Szóval nem túl rózsás a szénám, szívesen fogadok segítséget, kitartok, ha bírjátok még a bénázásom...

Köszi, Z.


________________________________
Feladó: Benjamin Szabo <notifications@github.com>
Elküldve: 2018. augusztus 2., csütörtök 15:48
Címzett: szabbenjamin/ittotttv
Másolatot kap: grape77; Mention
Tárgy: Re: [szabbenjamin/ittotttv] Stream URL token + PVR IPTV Simple Client (#6)


@grape77<https://github.com/grape77>
Ha osmc-t használsz:
ssh-n (putty) bejelentkezel
cd /home/osmc/ittotttv
git pull origin master

Ha hibát dob pullozáskor (conflict) akkor a felsorolt fájlokat egyesével törölgesd vagy
git reset --hard origin/master
és utána csekkold le a config fájlt, indítsd újra a gépet és készen is vagy.

**Comment by tamasdxw** [comment]
Nem hasznaltam meg OSMCt, de gondolom ha sudo-zol, lesz jogod irni.

cd /home/osmc/ittotttv
sudo bash
git pull origin master

**Comment by szabbenjamin** [comment]
@grape77 
Simán git pull origin master elég lett volna, semmit nem kellett volna újrahúzni.
